//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfDataExtractorCP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultExtractorDefinitionsSaveFolder {
            get {
                return ((string)(this["DefaultExtractorDefinitionsSaveFolder"]));
            }
            set {
                this["DefaultExtractorDefinitionsSaveFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultExtractorOutputFolder {
            get {
                return ((string)(this["DefaultExtractorOutputFolder"]));
            }
            set {
                this["DefaultExtractorOutputFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveFormLocationsOnExit {
            get {
                return ((bool)(this["SaveFormLocationsOnExit"]));
            }
            set {
                this["SaveFormLocationsOnExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultDataSourceType {
            get {
                return ((string)(this["DefaultDataSourceType"]));
            }
            set {
                this["DefaultDataSourceType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainFormHeight {
            get {
                return ((int)(this["MainFormHeight"]));
            }
            set {
                this["MainFormHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainFormWidth {
            get {
                return ((int)(this["MainFormWidth"]));
            }
            set {
                this["MainFormWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainFormX {
            get {
                return ((int)(this["MainFormX"]));
            }
            set {
                this["MainFormX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainFormY {
            get {
                return ((int)(this["MainFormY"]));
            }
            set {
                this["MainFormY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MessageLogHeight {
            get {
                return ((int)(this["MessageLogHeight"]));
            }
            set {
                this["MessageLogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MessageLogWidth {
            get {
                return ((int)(this["MessageLogWidth"]));
            }
            set {
                this["MessageLogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MessageLogX {
            get {
                return ((int)(this["MessageLogX"]));
            }
            set {
                this["MessageLogX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MessageLogY {
            get {
                return ((int)(this["MessageLogY"]));
            }
            set {
                this["MessageLogY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int MessageLogDefaultHeight {
            get {
                return ((int)(this["MessageLogDefaultHeight"]));
            }
            set {
                this["MessageLogDefaultHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("570")]
        public int MessageLogDefaultWidth {
            get {
                return ((int)(this["MessageLogDefaultWidth"]));
            }
            set {
                this["MessageLogDefaultWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowOutputLog {
            get {
                return ((bool)(this["ShowOutputLog"]));
            }
            set {
                this["ShowOutputLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowInstalledDatabaseProvidersOnly {
            get {
                return ((bool)(this["ShowInstalledDatabaseProvidersOnly"]));
            }
            set {
                this["ShowInstalledDatabaseProvidersOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreviewAllRows {
            get {
                return ((bool)(this["PreviewAllRows"]));
            }
            set {
                this["PreviewAllRows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LimitPreviewRows {
            get {
                return ((bool)(this["LimitPreviewRows"]));
            }
            set {
                this["LimitPreviewRows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int MaxNumberOfRows {
            get {
                return ((int)(this["MaxNumberOfRows"]));
            }
            set {
                this["MaxNumberOfRows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultDataDestinationType {
            get {
                return ((string)(this["DefaultDataDestinationType"]));
            }
            set {
                this["DefaultDataDestinationType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font DefaultApplicationFont {
            get {
                return ((global::System.Drawing.Font)(this["DefaultApplicationFont"]));
            }
            set {
                this["DefaultApplicationFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int BatchSizeForDataImportsAndExports {
            get {
                return ((int)(this["BatchSizeForDataImportsAndExports"]));
            }
            set {
                this["BatchSizeForDataImportsAndExports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50000")]
        public int BatchSizeForRandomDataGeneration {
            get {
                return ((int)(this["BatchSizeForRandomDataGeneration"]));
            }
            set {
                this["BatchSizeForRandomDataGeneration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultSourceAccessDatabaseFolder {
            get {
                return ((string)(this["DefaultSourceAccessDatabaseFolder"]));
            }
            set {
                this["DefaultSourceAccessDatabaseFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultSourceExcelDataFileFolder {
            get {
                return ((string)(this["DefaultSourceExcelDataFileFolder"]));
            }
            set {
                this["DefaultSourceExcelDataFileFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultSourceDelimitedTextFileFolder {
            get {
                return ((string)(this["DefaultSourceDelimitedTextFileFolder"]));
            }
            set {
                this["DefaultSourceDelimitedTextFileFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultSourceFixedLengthTextFileFolder {
            get {
                return ((string)(this["DefaultSourceFixedLengthTextFileFolder"]));
            }
            set {
                this["DefaultSourceFixedLengthTextFileFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultDestinationAccessDatabaseFolder {
            get {
                return ((string)(this["DefaultDestinationAccessDatabaseFolder"]));
            }
            set {
                this["DefaultDestinationAccessDatabaseFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultDestinationExcelDataFileFolder {
            get {
                return ((string)(this["DefaultDestinationExcelDataFileFolder"]));
            }
            set {
                this["DefaultDestinationExcelDataFileFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultDestinationDelimitedTextFileFolder {
            get {
                return ((string)(this["DefaultDestinationDelimitedTextFileFolder"]));
            }
            set {
                this["DefaultDestinationDelimitedTextFileFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultDestinationFixedLengthTextFileFolder {
            get {
                return ((string)(this["DefaultDestinationFixedLengthTextFileFolder"]));
            }
            set {
                this["DefaultDestinationFixedLengthTextFileFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultQueryDefinitionsFolder {
            get {
                return ((string)(this["DefaultQueryDefinitionsFolder"]));
            }
            set {
                this["DefaultQueryDefinitionsFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultDataGridExportFolder {
            get {
                return ((string)(this["DefaultDataGridExportFolder"]));
            }
            set {
                this["DefaultDataGridExportFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MyExtract")]
        public string DefaultExtractorDefinitionName {
            get {
                return ((string)(this["DefaultExtractorDefinitionName"]));
            }
            set {
                this["DefaultExtractorDefinitionName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultInputDatabaseType {
            get {
                return ((string)(this["DefaultInputDatabaseType"]));
            }
            set {
                this["DefaultInputDatabaseType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultInputDatabaseConnectionString {
            get {
                return ((string)(this["DefaultInputDatabaseConnectionString"]));
            }
            set {
                this["DefaultInputDatabaseConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultOutputDatabaseType {
            get {
                return ((string)(this["DefaultOutputDatabaseType"]));
            }
            set {
                this["DefaultOutputDatabaseType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultOutputDatabaseConnectionString {
            get {
                return ((string)(this["DefaultOutputDatabaseConnectionString"]));
            }
            set {
                this["DefaultOutputDatabaseConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OverwriteOutputDestinationIfAlreadyExists {
            get {
                return ((bool)(this["OverwriteOutputDestinationIfAlreadyExists"]));
            }
            set {
                this["OverwriteOutputDestinationIfAlreadyExists"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultSourceXmlFileFolder {
            get {
                return ((string)(this["DefaultSourceXmlFileFolder"]));
            }
            set {
                this["DefaultSourceXmlFileFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultDestinationXmlFileFolder {
            get {
                return ((string)(this["DefaultDestinationXmlFileFolder"]));
            }
            set {
                this["DefaultDestinationXmlFileFolder"] = value;
            }
        }
    }
}
